server:
  port: ${CUSTOM.SERVER.PORT:9010}

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://host.docker.internal:8761/eureka}
    fetchRegistry: true
    healthcheck:
      enable: true
    refresh:
      enable: true

### Mongo database configuration
spring:
  data:
    mongodb:
      #host: localhost
      host: host.docker.internal
      port: 27017
      database: mitocode
      uri: mongodb://mitocode:mitocode@host.docker.internal:27017
      authentication-database: admin

# Kafka Configuration
kafka:
  mitocode:
    topic: mitocode
    server: host.docker.internal
    port: 29092
